# Generated by Django 3.1.7 on 2021-03-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_place', models.CharField(max_length=200)),
                ('country_place', models.CharField(max_length=20)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptids.animal')),
            ],
        ),
    ]
