# Generated by Django 3.1.7 on 2021-03-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptids', '0005_animal_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptids.animal')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptids.location')),
            ],
        ),
    ]
